imports:
  - { resource: languages.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: queue.yml }
  - { resource: default_config.yml }
  - { resource: expert_config.yml }
  - { resource: ../../data/config.yml }

framework:
  secret: ThisTokenIsNotSoSecretChangeIt
  validation:
     enable_annotations: true
#     translation_domain: messages
  session:
    handler_id: '%session.handler_id%'
    save_path: '%data_directory%/sessions'
  form: ~
  csrf_protection: true
  assets: ~
  templating:
    engines: ['twig']
  translator:
    fallbacks: ['%locale%']
    paths:
      - '%kernel.root_dir%/../vendor/runalyze/translations/xlf'
      - '%kernel.root_dir%/../vendor/runalyze/translations/gettext'
  cache:
    pools:
      app.cache.activity_uploads:
        adapter: cache.app
        public: true
        default_lifetime: 86400

parameters:
  RUNALYZE_VERSION: 4.3.0

twig:
  globals:
    RUNALYZE_VERSION: '%RUNALYZE_VERSION%'
    garmin_api_key: '%garmin_api_key%'
    openweathermap_api_key: '%openweathermap_api_key%'
    meteostatnet_api_key: '%meteostatnet_api_key%'
    darksky_api_key: '%darksky_api_key%'
    nokia_here_appid: '%nokia_here_appid%'
    nokia_here_token: '%nokia_here_token%'
    thunderforest_api_key: '%thunderforest_api_key%'
    mapbox_api_key: '%mapbox_api_key%'
    locales: '%locales%'
    osm_overpass_url: '%osm_overpass_url%'
    osm_overpass_proxy: '%osm_overpass_proxy%'
  paths:
    '%data_directory%/views': __main__
  form_themes:
     - 'form/fields.html.twig'

# Doctrine Configuration
doctrine_cache:
    providers:
        vendor_filesystem_metadata_cache:
            file_system:
                extension: cache
                directory: "%kernel.root_dir%/../var/cache/doctrine"
        vendor_filesystem_result_cache:
            file_system:
                extension: cache
                directory: "%kernel.root_dir%/../var/cache/doctrine"
        vendor_filesystem_query_cache:
            file_system:
                extension: cache
                directory: "%kernel.root_dir%/../var/cache/doctrine"

doctrine:
    dbal:
        default_connection:   default

        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                options: {1002: "SET time_zone = '+00:00'"}
                mapping_types:
                    enum:   string
        types:
            casted_decimal_1: Runalyze\Bundle\CoreBundle\Doctrine\Types\CastedDecimalScale1Type
            casted_decimal_2: Runalyze\Bundle\CoreBundle\Doctrine\Types\CastedDecimalScale2Type
            tinyint: Runalyze\Bundle\CoreBundle\Doctrine\Types\TinyIntType
            pipe_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\PipeDelimitedArray
            geohash_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\GeohashArray
            runalyze_pause_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\RunalyzePauseArray
            runalyze_round_array: Runalyze\Bundle\CoreBundle\Doctrine\Types\RunalyzeRoundArray


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        metadata_cache_driver:
            type: service
            id: doctrine_cache.providers.vendor_filesystem_metadata_cache
        result_cache_driver:
            type: service
            id: doctrine_cache.providers.vendor_filesystem_result_cache
        query_cache_driver:
            type: service
            id: doctrine_cache.providers.vendor_filesystem_query_cache
        hydrators:
            COLUMN_HYDRATOR: Runalyze\Bundle\CoreBundle\Doctrine\Hydrator\ColumnHydrator
        dql:
            datetime_functions:
                from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                month: DoctrineExtensions\Query\Mysql\Month
                week: DoctrineExtensions\Query\Mysql\Week
                year: DoctrineExtensions\Query\Mysql\Year
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
                round: DoctrineExtensions\Query\Sqlite\Round

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Runalyze\Migrations
    table_name: '%database_prefix%migration_versions'
    column_name: 'version'
    name: RUNALYZE Migrations

monolog:
    channels: ['queue', 'console', 'external_services', 'activity_uploads']
    handlers:
        applog:
            type: rotating_file
            path: '%kernel.root_dir%/../var/logs/symfony.log'
            level: error
            max_files: 7
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
        queue:
            type: rotating_file
            level: debug
            path: '%kernel.root_dir%/../var/logs/queue.log'
            max_files: 7
            channels: ['queue']
        console:
            type: rotating_file
            level: error
            path: '%kernel.root_dir%/../var/logs/console.log'
            max_files: 7
            channels: ['console']
        external_services:
            type: rotating_file
            level: warning
            path: '%kernel.root_dir%/../var/logs/external_services.log'
            max_files: 7
            channels: ['external_services']
        activity_uploads:
            type: rotating_file
            level: debug
            path: '%kernel.root_dir%/../var/logs/activity_uploads.log'
            max_files: 7
            channels: ['activity_uploads']

swiftmailer:
    transport:            smtp
    username:             '%smtp_username%'
    password:             '%smtp_password%'
    host:                 '%smtp_host%'
    port:                 '%smtp_port%'
    encryption:           '%smtp_security%'
    sender_address:       '%mail_sender%'
    local_domain:         '%mail_localdomain%'

jms_translation:
    configs:
        app:
            dirs: ['%kernel.root_dir%/', '%kernel.root_dir%/../src']
            output_dir: '%kernel.root_dir%/../vendor/runalyze/translations/xlf'
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs, test, doctrine]
            output-format: 'xlf'

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis.default.dsn%'
